### ISSUE TITLE
snap installation on Ubuntu does not place asmpp.pl and asmstyle.pl in /snap/bin

### ISSUE THREAD

**Issue by iratahack** [z88dk/z88dk#1797]
When installing z88dk on Ubuntu with the command below the two perl scripts, _asmpp.pl_ and _asmstyle.pl_ are not included in the _/snap/bin_ directory.

`sudo snap install --edge z88dk`

I assume the file below creates the snap image but I'm not familiar with the format.

https://github.com/iratahack/z88dk/blob/master/snap/snapcraft.yaml

Maybe adding the following is all that's needed?

```
  asmpp.pl:
    command: bin/asmpp.pl
    plugs: [home, removable-media]
  asmstyle.pl:
    command: bin/asmstyle.pl
    plugs: [home, removable-media]

```
